# async 关键字

async 关键字用于简化异步操作, 是 Promise API 的语法糖.

async 函数的各种写法:

```js
async function fun1() {} // 普通函数

const fun2 = async function () {}; // 函数表达式

const fun3 = async () => {}; // 箭头函数

const obj = { async fun4() {} }; // 对象方法

class MyClass {
    async fun5() {} // 类方法
}
```

<br>

async 修饰的函数始终返回 Promise 实例, 为异步函数.

async 函数的返回值会被 `Promise.resolve()` 包装成一个 Promise 实例, 如果没有 return 语句则会返回 undefined.

```js
async function show() {
    return "ok"; // 返回非 Promise 实例的数据
}
const p1 = show();
console.log("p1", p1); // p1 Promise {<fulfilled>: 'ok'}
```

相当于:

```js
const p2 = new Promise((resolve) => {
    resolve("ok");
});
console.log("p2", p2); // p2 Promise {<fulfilled>: 'ok'}
```

<br>

如果异步函数内部抛出错误, 会返回 rejected 状态的 Promise 实例, 值为抛出的错误信息.

```js
async function show() {
    throw "出错了"; // 抛出异常
}
const p1 = show();
console.log("p1", p1); // p1 Promise {<rejected>: '出错了'}
```

相当于:

```js
const p2 = new Promise((_, reject) => {
    reject("出错了");
});
console.log("p2", p2); // p2 Promise {<rejected>: '出错了'}
```

<br>

如果 async 函数返回 fulfilled 状态的 Promise 实例:

```js
async function show() {
    return Promise.resolve("ok");
}
const p1 = show();
console.log("p1", p1); // p1 Promise {<pending>}
setTimeout(console.log, 0, "p1", p1); // Promise {<fulfilled>: 'ok'}
```

相当于:

```js
const p1 = new Promise((resolve) => {
    resolve("ok");
}).then((res) => {
    return res;
});
console.log("p1", p1); // p1 Promise {<pending>}
setTimeout(console.log, 0, "p1", p1); // Promise {<fulfilled>: 'ok'}
```

如果 async 函数返回 rejected 状态的 Promise 实例:

```js
async function show() {
    return Promise.reject("fail");
}
const p1 = show();
console.log("p1", p1); // p1 Promise {<pending>}
setTimeout(console.log, 0, "p1", p1); // p1 Promise {<rejected>: 'fail'}
```

相当于:

```js
const p1 = new Promise((resolve) => {
    resolve("fail");
}).then((res) => {
    return Promise.reject(res);
});
console.log("p1", p1); // p1 Promise {<pending>}
setTimeout(console.log, 0, "p1", p1); // p1 Promise {<rejected>: 'fail'}
```

<br><br>

# await 关键字

我们可以在 async 函数的**直接子作用域**中, 使用 await 关键字来控制异步操作的执行.

```js
async function fun() {
    const res = await 1;
    console.log("res", res);
}

console.log("start");
fun();
console.log("end");
```

相当于:

```js
console.log("start");

new Promise((resolve) => {
    resolve(1);
}).then((res) => {
    console.log("res", res);
});

console.log("end");
```

<br>

```js
async function fun() {
    const res = await Promise.resolve(1);
    console.log("res", res);
}

console.log("start");
fun();
console.log("end");
```

相当于:

```js
console.log("start");

new Promise((resolve) => {
    resolve();
})
    .then(() => {
        return 1;
    })
    .then((res) => {
        console.log("res", res);
    });

console.log("end");
```

<br>

```js
async function test() {
    console.log("before await");
    const val1 = await new Promise((resolve) => {
        setTimeout(() => {
            resolve("ProResolve");
        }, 1000);
    });
    console.log(val1);
    console.log("after await");
}

console.log("before async");
test();
console.log("after async");
```

上例等效于:

```js
console.log("before async");

new Promise((resolve) => {
    console.log("before await");
    resolve();
})
    .then(() => {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve("ProResolve");
            }, 1000);
        });
    })
    .then((val1) => {
        console.log("val1", val1);
        console.log("after await");
    });

console.log("after async");
```

<br>

如果 await 右边的 Promise 实例状态变成了 fulfilled, await 关键字会返回该 Promise 实例的值；如果 Promise 实例状态变成了 rejected, await 关键字会抛出错误.

```js
async function show() {
    const res = await Promise.reject("wrong"); // 这里抛出错误, 后面的语句都不会执行
    console.log("res", res); // 这里不会打印
}
show();
```

可以使用 Promise 实例调用 catch 方法处理错误:

```js
async function show() {
    const res = await Promise.reject("wrong").catch((rea) => rea);
    console.log("res", res); // res wrong
}
show();
```

也可以通过 `try … catch` 语句捕获并处理错误:

```js
async function show() {
    try {
        const res = await Promise.reject("wrong"); // 这里抛出错误, 后面的语句都不会执行
        console.log("res", res); // 这里不会打印
    } catch (error) {
        console.log("error", error); // error wrong
    }
}
show();
```

<br><br>

# await 使用陷阱

1. 对于并行执行的异步任务, 其实并不适合用 await 修饰

```js
async function fun() {
    const pro1 = await fetch("url1");
    const pro2 = await fetch("url2");
    // ...
}
```

上例这样写, 虽没有错误, 但会打破两个 fetch 的并行, 这需要等待第 1 个异步任务执行完毕之后, 才会执行第 2 个异步任务
所以我们可以不用 await 修饰这些并行执行的异步操作

```js
async function fun() {
    const proA = fetch("url1"); // 只要不加 await, Ajax 就会同时请求
    const proB = fetch("url2");
    const pro1 = await proA;
    const pro2 = await proB;
    console.log(pro1, pro2);
    // ...
}
```

这里更高效的做法: 通过 `Promise.all` 组合起来

```js
async function fun() {
    const proA = fetch("url1"); // 只要不加 await, Ajax 就会同时请求
    const proB = fetch("url2");
    const [pro1, pro2] = await Promise.all([proA, proB]);
    // ...
}
```

<br>

2. 如果我们需要在循环中执行异步操作, 是不能够直接调用 `forEach` / `map` 这一类方法的. 即使我们在回调函数中写了 `await`, `forEach` 也会立刻返回, 并不会暂停等到所有异步操作都执行完毕.

```js
async function fun() {
    [1, 2, 3].forEach(async (i) => {
        await someAsyncOperation();
    });
    console.log("done");
}
fun();
```

如果我们希望等待循环中的异步操作都完成之后才继续执行, 那我们还是应该使用传统的 `for` 循环

```js
async function fun() {
    for (let i of [1, 2, 3]) {
        await someAsyncOperation();
    }
    console.log("done");
}
fun();
```

更进一步, 如果我们想所有操作都并发执行, 可以使用 `for await`:
这里的 `for` 循环依然会等到所有的异步操作都完成之后才继续向后执行

```js
async function fun() {
    const pros = [someAsyncOperation1, someAsyncOperation2, someAsyncOperation3];
    for await (let result of pros) {
        // ...
    }
    console.log("done");
}
fun();
```

<br><br>

# DEMO

**demo1**: 读取多个文件

使用回调函数读取多个文件

```js
const fs = require("fs");

fs.readFile("./demo.html", (err, data1) => {
    if (err) throw err;
    fs.readFile("./demo.html", (err, data2) => {
        if (err) throw err;
        fs.readFile("./demo.html", (err, data3) => {
            if (err) throw err;
            console.log(data1 + data2 + data3);
        });
    });
});
```

使用 async & await 读取多个文件:

```js
const fs = require("fs");
const util = require("util");

// 把 fs.readFile 方法封装成 Promise 实例
const myReadFile = util.promisify(fs.readFile);

async function main() {
    try {
        const data1 = await myReadFile("./demo.html");
        const data2 = await myReadFile("./demo.html");
        const data3 = await myReadFile("./demo.html");
        console.log(data1 + data2 + data3);
    } catch (error) {
        console.log(error);
    }
}

main();
```

<br>

**demo2**:

```js
async function foo() {
    console.log(2);
    await null;
    console.log(4);
}

console.log(1);
foo();
console.log(3);
```

相当于:

```js
new Promise((resolve) => {
    console.log(2);
    resolve(null);
}).then(() => {
    console.log(4);
});

console.log(3);
```

<br>

**demo3**:

```js
async function foo() {
    console.log(2);
    console.log(await Promise.resolve(8));
    console.log(9);
}
async function bar() {
    console.log(4);
    console.log(await 6);
    console.log(7);
}

console.log(1);
foo();
console.log(3);
bar();
console.log(5);
```

相当于:

```js
console.log(1);

new Promise((resolve, reject) => {
    console.log(2);
    resolve();
})
    .then(() => {
        return 8;
    })
    .then((data) => {
        console.log(data);
        console.log(9);
    });

console.log(3);

new Promise((resolve, reject) => {
    console.log(4);
    resolve(6);
}).then((data) => {
    console.log(data);
    console.log(7);
});

console.log(5);
```

<br>

**demo4**:

```js
async function asy1() {
    console.log(1);
    await asy2();
    console.log(2);
}

const asy2 = async () => {
    await setTimeout(() => {
        Promise.resolve().then(() => {
            console.log(3);
        });
        console.log(4);
    }, 0);
};

const asy3 = async () => {
    Promise.resolve().then(() => {
        console.log(6);
    });
};

asy1();
console.log(7);
asy3();
```

```js
console.log(1);

const timer = setTimeout(() => {
    Promise.resolve().then(() => {
        console.log(3);
    });
    console.log(4);
}, 0);

new Promise((resolve) => {
    resolve(timer);
}).then(() => {
    new Promise((resolve) => {
        resolve(undefined);
    }).then(() => {
        console.log(2);
    });
});

console.log(7);

Promise.resolve().then(() => {
    console.log(6);
});
```

【async - await 面试题】https://www.bilibili.com/video/BV1Hu4y1s7oR?vd_source=1cfaaba48b356e45a1b23a0060ed3b27

<br>

**demo5**:

```js
async function asy1() {
    console.log(1);
    await asy2();
    console.log(2);
}

const asy2 = async () => {
    await (async () => {
        await (() => {
            console.log(3);
        })();
        console.log(4);
    })();
};

const asy3 = async () => {
    Promise.resolve().then(() => {
        console.log(6);
    });
};

asy1();
console.log(7);
asy3();
```

```js
console.log(1);
console.log(3);
new Promise((resolve) => {
    resolve(undefined);
}).then(() => {
    console.log(4);
    new Promise((resolve) => {
        resolve(undefined);
    }).then(() => {
        new Promise((resolve) => {
            resolve(undefined);
        }).then(() => {
            console.log(2);
        });
    });
});

console.log(7);

Promise.resolve().then(() => {
    console.log(6);
});
```

【async - await 面试题】https://www.bilibili.com/video/BV1Hu4y1s7oR?vd_source=1cfaaba48b356e45a1b23a0060ed3b27
